// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLQ95Cdf5F5Ed3osOGQZAXPOnKFsoqoiY',
    appId: '1:842540261392:web:a8b413f8997b97f7c12a95',
    messagingSenderId: '842540261392',
    projectId: 'pulse-employee-app',
    authDomain: 'pulse-employee-app.firebaseapp.com',
    databaseURL: 'https://pulse-employee-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pulse-employee-app.appspot.com',
    measurementId: 'G-8Y87WLC6HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBReS-N_OkayZwETCZN8iSLvUTgE3HHwvM',
    appId: '1:842540261392:android:a8dab0f90ff187a2c12a95',
    messagingSenderId: '842540261392',
    projectId: 'pulse-employee-app',
    databaseURL: 'https://pulse-employee-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pulse-employee-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS1dAKuQiIbn2PbFOn4fooxwfMGMqeLoY',
    appId: '1:842540261392:ios:ae4cf01e83767903c12a95',
    messagingSenderId: '842540261392',
    projectId: 'pulse-employee-app',
    databaseURL: 'https://pulse-employee-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pulse-employee-app.appspot.com',
    iosBundleId: 'com.example.conclave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS1dAKuQiIbn2PbFOn4fooxwfMGMqeLoY',
    appId: '1:842540261392:ios:4877563161ee9ca1c12a95',
    messagingSenderId: '842540261392',
    projectId: 'pulse-employee-app',
    databaseURL: 'https://pulse-employee-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pulse-employee-app.appspot.com',
    iosBundleId: 'com.example.conclave.RunnerTests',
  );
}
